### PR TITLE
Implement command for patient creation

### LINKED ISSUE #14: Implement registration of new patients in Java
https://github.com/BelinaJaroslav/DBS_2020/issues/8

# Validations
- non-empty name
- non-empty surname
- birth_number is a number (divisibility by 11 is not required)
- vaccine_id exists in DB
- doctor_id exists in DB
- time is valid

### PR DESCRIPTION
**Pull request by domcermak**
#14

### CODE REVIEW

**Review by BelinaJaroslav — COMMENTED** [review]
When creating a patient, the IDs generate above 1000

**Review by BelinaJaroslav — APPROVED** [review]
function-wise lgtm

**Comment by domcermak** [comment]
Id is generated by the DB itself. I can do nothing about it. Maybe explicit seed would help. But I would not even consider it as an issue.

**Comment by BelinaJaroslav** [comment]
That was what I thought, but wanted to make sure

**Pull request merged**
